generator_type: tf

controller_frequency: 50 # Possibly change to 20

# tf_prefix: wamv

cg_link: cg_link

odometry_source: /odometry/filtered/local

enabled: false

control_modes:
  idle: false

  flight:
    surge:    {p: 20.0,    i: 5.0,   d: 2.0,   i_max: 30, i_min: -30}
    yaw:      {p: 20.0,    i: 2.0,   d: 15.0,  i_max: 30, i_min: -30}
  
  hold_xy:
    x:        {p: 2.5,    i: 1.0,   d: 5.0,   i_max: 10, i_min: -10}
    y:        {p: 2.5,    i: 1.0,   d: 5.0,   i_max: 10, i_min: -10}

  hold_dof:
    surge:    {p: 20.0,    i: 5.0,   d: 2.0,    i_max: 30, i_min: -30}
    yaw:      {p: 20.0,    i: 2.0,   d: 15.0,   i_max: 30, i_min: -30}

##
# THRUSTERS
##
thruster_ids:
  - thruster_starboard
  - thruster_port

control_tf:
  thruster_starboard: thruster_starboard_link
  thruster_port: thruster_port_link

thruster_command_topics:
  thruster_starboard: control/thruster/starboard
  thruster_port: control/thruster/port

thruster_force_topics:
  thruster_starboard: control/force/starboard
  thruster_port: control/force/port


##
# Polynomials for each thruster.
#
# Quadratic Programming Optimization computes the thrust
# required. We need to turn that number into thruster command.
# Setpoint commands in this system defined between -1 and 1.
#
# y axis of the polynomial , f(x) = y, should be in Newton.
#
# Take the polynomial
# f(x) = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0
#
# Array would hold the lower degrees in lower indexes. Shown below:
# [a_0, a_1, ... ,a_(n-1), a(n)]
#   f(x) = a5*x^5 + a4*x^4 + a3*x^3 + a2*x^2 + a1*x + a0
#
# For T200 bluerobotics thrusters:
# Curve fitting results:
#   a0 =      0.06165
#   a1 =      20.32
#   a2 =      9.632
#   a3 =      93.05
#   a4 =      -2.856
#   a5 =      -74.1
#
# For T500 bluerobotics thrusters:
# Curve fitting results:
#   a0 =      -0.03703
#   a1 =      4.217
#   a2 =      2.84
#   a3 =      4.976
#   a4 =      -0.4119
#   a5 =      -0.8448
#
##
thruster_polynomials:
  # surge:        [0.5038, 31.49, 29.78, 139.5, -18.66, -113.1]
  thruster_starboard:    [0.5038, 31.49, 29.78, 139.5, -18.66, -113.1] # [-0.03703, 4.217, 2.84, 4.976, -0.4119, -0.8448]
  thruster_port:    [0.5038, 31.49, 29.78, 139.5, -18.66, -113.1] # [-0.03703, 4.217, 2.84, 4.976, -0.4119, -0.8448]

## Force limits
thruster_limits:
  # surge:
  #   max: 50
  #   min: -10
  thruster_starboard:
    max: 50
    min: -50
  thruster_port:
    max: 50
    min: -50