# This file defines states and attached behaviors and priorities for helm

helm_configuration:
  frequency: 10.0
  global_link: world_ned
  local_link: cg_link

finite_state_machine:
  - name: start
    mode: idle
    initial: true
    transitions:
      - survey_3d
      - kill

  - name: survey_3d
    mode: flight
    transitions:
      - start
      - kill

  - name: kill
    mode: idle
    transition:
      - start

  - name: direct_control
    mode: hold_dof
    transitions:
      - start
      - kill

behaviors:
  - name: path_3d
    plugin: helm::PathFollowing3D
    states:
      - { name: survey_3d, priority: 1 }

  - name: gps_wpt
    plugin: helm::GpsWaypoint
    states:
      - { name: survey_3d, priority: 1 }

  - name: direct_control
    plugin: helm::DirectControlCont
    states:
      - { name: direct_control, priority: 1 }